### ISSUE TITLE
add rtlsdr support

### ISSUE THREAD

**Issue by jbrzusto** [jbrzusto/sensorgnome#13]
## Minimalist (?) approach ##
Incorporate rtlsdr into VAH control framework by running one rtl_tcp per rtlsdr dongle and having
VAH pull data from each using a unix domain socket.  Unlike using librtlsdr directly, this approach:
- provides an fd to use in VAH's poll() call
- provides asynchronous rtlsdr settings accessible directly from the nodejs master process, so we can avoid coding another fcd-style external executable.

The initial target is RPi 2/3 (I'm not sure beaglebone will be up to the extra context-switching
from running multiple copies of rtl_tcp).

### Sketch ###

- [x] add stable (bus/dev) device selection to librtlsdr (i.e. need to know which device is in e.g. USB port 3); **done:** https://github.com/jbrzusto/librtlsdr/commit/30cf0c1240f13684588404a8fb40c90c2ea89498
- [x] add command-line bus/dev device selectors to rtl_tcp; **done:** transparent via device "index" parsing in librtlsdr, so applies to all rtlsdr executables
- [x] add option for unix_domain socket to rtl_tcp (lower-overhead transport between rtl_tcp and VAH)
  **done:**  https://github.com/jbrzusto/librtlsdr/commit/7f53b0c016bb3e5786d7e2ef4a79bb2affbe2139 which just parses the port number more liberally, allowing a path
- [x] choose and implement scheme for rtl_tcp to get commands from one process (nodejs) while sending I/Q samples to another (VAH) - see next comment for details.
  **done:** https://github.com/jbrzusto/librtlsdr/commit/3ce90d7db6bcbb9f39693551a4e84fd531f32b3e and https://github.com/jbrzusto/librtlsdr/commit/b123eab2840f3e7bb178cf17a543b68403efe3e8
~~- [ ] create RTLSDRMinder.cpp in https://github.com/jbrzusto/vamp-alsa-host to grab I/Q samples
from rtl_tcp (don't forget to skip or verify the rtl_tcp header...)~~
~~- [ ] extend VampAlsaHost to allow opening an RTLSDRMinder and attaching plugins to it
  (maybe use more liberal parsing on device argument to 'open', allowing e.g. **rtlsdr1:5**)~~
- [x] refactor AlsaMinder into DevMinder and hardware dependent subclass AlsaMinder
   **done:** https://github.com/jbrzusto/vamp-alsa-host/commit/cafbcfbf9be99d17310d9e318a67237920d69fb4
- [x] add new subclass DevMinder::RTLSDRMinder to handle grabbing data from rtl_tcp
  **done:** https://github.com/jbrzusto/vamp-alsa-host/commit/6d21aeaa3fe5bbe22515553daab1e638a77bb5e4
   RTLSDR Device can be opened, samples streamed, and plugins attached.
   Pulses detected show symptoms of possible issues:
        - time reversals
        -  negative frequency offset for detected pulses when listening at 166.376 MHz
- [x] add udev rules to create appropriate device in /dev/bonedongle
  **done:** https://github.com/jbrzusto/sensorgnome-pi/commit/128af8e784bc3c92b9b6420bdfe4eb69af056a7f
- [x] support listing rtlsdr devices by scripts/get_hub_devices.pl and modify client-side sensorgnome.js to display rtlsdr dongle in device list
  **done:** https://github.com/jbrzusto/sensorgnome-pi/commit/fdc335875f6f21294dd07258475c608c4da3706c
~~- [ ] modify master/usbaudio.js class to launch rtl_tcp with appropriate bus/dev for each rtlsdr dongle,
       and support scheduled parameter settings~~
- [x] refactor master/usbaudio.js into sensor.js and hardware-specific subclass
      usbaudio.js
      **done:** https://github.com/jbrzusto/sensorgnome/commit/5d4cc05c47fa33802ae9e42f33cf295962f54143
- [x] add new subclass rtlsdr.js of sensor.js
- [x] add support for acting on an rtlsdr plan parsed from deployment.txt
- [x] use "S" records in raw output to indicate use of rtlsdr and its parameters, as done with funcubes
(implicit in other changes)
- [x] have web interface show param settings
- [x] add web interface controls for changing params 
**done:** https://github.com/jbrzusto/sensorgnome/commit/6b9dd4ddb9debfb7b708cf56f03d0d94c22c0a48
- [x] have librtlsdr and rtl_tcp tag buffers with CLOCK_REALTIME of urb completion and then send() it along
with data so RTLSDRMinder  can use it.  ~~Maybe switch from SOCK_STREAM TO SOCK_DGRAM~~ (removed in node 0.6)  ~~or SOCK_SEQPACKET~~ (not supported by node 0.10) to simplify pulling timestamps out of data?  We'll have to just include the sample count in the data sent.  Yuck.
**done:** https://github.com/jbrzusto/librtlsdr/commit/bfc94633acb6e944e8d3245c6497e496fc2bd2e5
- [x] package ~~as an update to the RPi SG image~~ 
**done**: part of the April 30 release at http://public.sensorgnome.org/Raspberry_Pi_Sensorgnome/
with details here: https://sensorgnome.org/index.php?title=The_Raspberry_Pi_2_%2F%2F_3_as_a_Sensorgnome#section_6

----
### Performance ###
If rtl_tcp performance needs improvement, consider these possibilities:
    - switch to a single-threaded model using poll() on all relevant file descriptors, as VAH does.
    - switch to a static fixed-size ring buffer instead of the malloc-thrashing dynamic linked
       list of dynamically-allocated (on each callback from rtlsdr_read_async()!) buffers, as VAH does
    - why two levels of buffering: 1 for libusb, another for librtlsdr?
    - timing: grab current time for each libusb transfer completion.
    - or maybe, if we're going through this trouble, recode RTLSDRMinder to call librtlsdr directly!

**Comment by jbrzusto** [comment]
### Detail: two processes talking to the same rtl_tcp ###
VAH and nodejs can't share a connection to rtl_tcp (in particular, nodejs can't open a socket connection
and pass its file descriptor to a child_process), so how do we arrange that:
 - VAH can receive I/Q samples
 - nodejs can send gain/freq/rate etc. param settings

from/to the same rtl_tcp process?
### Possible Solutions ###
1. VAH owns the connection; nodejs sends rtlsdr settings via new commands added to VAH
2. rtl_tcp opens two unix domain sockets, with paths parsed from two -p options;
   - connections on both sockets are effectively half-duplex
   - first socket's connection is for sending I/Q samples
   - second socket's connection is for receiving param commands
3. rtl_tcp allows two simultaneous connections to the single socket and both connections 
     allow sending I/Q samples and receiving commands; optionally, add a "start"
     command and don't send I/Q samples until that command has been received.
4. rtl_tcp allows two simultaneous connections to the single socket;  the first connection receives commands; the second connection sends I/Q samples

(1) would take a fair amount of coding and is awkward. (4) has an obvious race condition:  whose
connection is first, but this can be managed by having nodejs create the first connection, and only then tell VAH to open the device  (3) is a bit inefficient in that it fills the I/Q buffer for writing to the connection that's being used to receive commands, even though the other end isn't reading from that connection. (using `select()`, that shouldn't matter; the fd should never be in the "writable" set once the buffer fills).  (2) is awkward in management of lapsed connections, and requires more changes than (4).
So we'll go with (4), and add a 'start' command to initiate streaming on the second connection.

**Comment by jbrzusto** [comment]
### Detail: Detaching Kernel Drivers from RTLSDR Devices ###

**2017-04-30**: we're now just blacklisting the rtl dvb driver, which I think
removes this issue, but the scheme below is still in effect.

Before rtlsdr support, we used udev rules to create symlinks to
supported sg devices in /dev/sensorgnome.  The /dev/sensorgnome
directory was watched by hubman.js to detect addition / removal of
supported devices.  For gps and funcubedongle devices, standard
kernel drivers were used by gpsd and vamp-alsa-host.

In contrast, librtlsdr talks directly to dongles as vanilla USB
devices, so uses libusb to detach the kernel drivers (e.g. dvb) from
them.  In our existing framework, this removed their symlinks in
/dev/sensorgnome, causing the master.js process to treat the devices
as having been removed, and so devices were removed as soon as an
rtl_tcp process was launched to control them.

So we adopt the following scheme for rtlsdr devices:
- plugging in an rtlsdr device triggers, for example:
   - touch an empty file in /dev/sensorgnome, e.g.
     touch /dev/sensorgnome/rtlsdr.port=2.usbPath=1:6.vidpid=0bda:2838.mfg=Realtek.prod=RTL2838UHIDIR
   - create symlink in /dev/sensorgnome/usb, e.g.
     /dev/sensorgnome/usb/2 -> /dev/sensorgnome/rtlsdr.port=2.usbPath=1:6.vidpid=0bda:2838.mfg=Realtek.prod=RTL2838UHIDIR
- unplugging an rtlsdr device triggers:
   - remove empty file in /dev/sensorgnome/, e.g.
     rm /dev/sensorgnome/rtlsdr.port=2.usbPath=1:6.vidpid=0bda:2838.mfg=Realtek.prod=RTL2838UHIDIR
   - remove symlink in /dev/sensorgnome/usb, e.g.:
     rm /dev/sensorgnome/usb/2

So far, this behaviour parallels that for gps and funcubes, except that
it's an empty file rather than a symlink created in /dev/sensorgnome,
and we create the additional symlink in /dev/sensorgnome/usb

The difference occurs when libusb detaches kernel drivers for the rtlsdr
device.  In that situation, although the drivers are detached, the
empty file and symlink above are preserved.  They continue to exist
if rtl_tcp re-attaches kernel drivers upon exit.

We could shift /dev/sensorgnome semantics to this scheme for all devices, not just
rtlsdr, but at present, it makes no difference.

**Comment by jbrzusto** [comment]
preliminary version working; screenshot here:

https://sensorgnome.org/@api/deki/files/14072/=2017-04-12_sg_pi_3_rtlsdr_1_funcube.png

### TODO ###
- DONE: package as an image ~~and update~~
- DONE: reduce libusb buffer size for (hopefully) better time precision
- DONE: maintain device settings on nodejs side, so we can send them to the web interface
- DONE: deal with race conditions in detaching plugin from a device which has already been removed
- move subsampling into rtl_tcp to spread load among cores
